services:
  - type: web
    name: collaborative-todo-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres.ovsnbcetazumscobnlbl:Jack@123456@aws-0-ap-south-1.pooler.supabase.com:6543/postgres
      - key: JWT_SECRET
        value: collaborative_todo_jwt_secret_key_2024_secure
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://collaborative-todo-frontend.vercel.app